
export const quizData = [
  { id: 1, question: "What is JavaScript?", answer: "JavaScript is a programming language used to add interactivity to web pages." },
  { id: 2, question: "Difference between var, let, and const?", answer: "var is function-scoped, let and const are block-scoped; const cannot be reassigned." },
  { id: 3, question: "What is hoisting?", answer: "Hoisting is JavaScript's behavior of moving declarations to the top of the scope." },
  { id: 4, question: "What are arrow functions?", answer: "Arrow functions are a shorter syntax for writing functions and do not bind their own 'this'." },
  { id: 5, question: "Difference between == and ===?", answer: "== checks for value equality with type coercion, === checks for strict equality without coercion." },
  { id: 6, question: "What is a promise?", answer: "A promise represents the eventual completion or failure of an asynchronous operation." },
  { id: 7, question: "What is async/await?", answer: "Async/await is syntax to handle asynchronous code in a synchronous-like manner." },
  { id: 8, question: "What is the DOM?", answer: "The DOM is the Document Object Model, representing the structure of a web page." },
  { id: 9, question: "What is an event loop?", answer: "The event loop handles asynchronous callbacks in JavaScript." },
  { id: 10, question: "What is closure?", answer: "A closure is a function that retains access to variables from its lexical scope." },
  { id: 11, question: "What is a callback function?", answer: "A callback is a function passed into another function to be executed later." },
  { id: 12, question: "What is the difference between null and undefined?", answer: "null is an assigned value, undefined means a variable has been declared but not assigned." },
  { id: 13, question: "What is NaN?", answer: "NaN stands for Not-a-Number, representing an invalid number result." },
  { id: 14, question: "What are template literals?", answer: "Template literals allow embedded expressions using backticks and ${} syntax." },
  { id: 15, question: "What is destructuring?", answer: "Destructuring allows unpacking values from arrays or objects into distinct variables." },
  { id: 16, question: "What are default parameters?", answer: "Default parameters allow functions to have default values if no argument is provided." },
  { id: 17, question: "What is the difference between for...in and for...of?", answer: "for...in iterates over object keys, for...of iterates over iterable values." },
  { id: 18, question: "What is a prototype in JavaScript?", answer: "Prototype is an object from which other objects inherit properties." },
  { id: 19, question: "What is event bubbling?", answer: "Event bubbling is when an event propagates from child to parent elements." },
  { id: 20, question: "What is event capturing?", answer: "Event capturing is when an event propagates from parent to child elements." },
  { id: 21, question: "What is localStorage?", answer: "localStorage stores data in the browser with no expiration date." },
  { id: 22, question: "What is sessionStorage?", answer: "sessionStorage stores data for the duration of the page session." },
  { id: 23, question: "What is JSON?", answer: "JSON stands for JavaScript Object Notation, used for data exchange." },
  { id: 24, question: "What is the difference between synchronous and asynchronous code?", answer: "Synchronous code runs sequentially, asynchronous code allows tasks to run independently." },
  { id: 25, question: "What is a generator function?", answer: "A generator function returns an iterator and can pause execution using yield." },
  { id: 26, question: "What is the difference between map and forEach?", answer: "map returns a new array, forEach executes a function without returning." },
  { id: 27, question: "What is reduce in JavaScript?", answer: "reduce executes a reducer function to accumulate array values into a single result." },
  { id: 28, question: "What is the difference between slice and splice?", answer: "slice returns a shallow copy, splice modifies the original array." },
  { id: 29, question: "What is typeof operator?", answer: "typeof returns the type of a variable or expression." },
  { id: 30, question: "What is instanceof operator?", answer: "instanceof checks if an object is an instance of a constructor." },
  { id: 31, question: "What is a module in JavaScript?", answer: "Modules are reusable pieces of code that can be imported and exported." },
  { id: 32, question: "What is strict mode?", answer: "Strict mode enforces stricter parsing and error handling in JavaScript." },
  { id: 33, question: "What is a shallow copy?", answer: "A shallow copy copies only references of nested objects, not the objects themselves." },
  { id: 34, question: "What is a deep copy?", answer: "A deep copy duplicates all nested objects and values." },
  { id: 35, question: "What is the difference between function declaration and function expression?", answer: "Declarations are hoisted, expressions are not." },
  { id: 36, question: "What is a pure function?", answer: "A pure function always returns the same output for the same input without side effects." },
  { id: 37, question: "What is immutability?", answer: "Immutability means data cannot be changed after creation." },
  { id: 38, question: "What is the difference between shallow equality and deep equality?", answer: "Shallow equality compares references, deep equality compares values recursively." },
  { id: 39, question: "What is a symbol in JavaScript?", answer: "Symbol is a primitive data type used for unique identifiers." },
  { id: 40, question: "What is BigInt?", answer: "BigInt is a numeric type that can represent integers beyond Number limits." },
  { id: 41, question: "What is the difference between call, apply, and bind?", answer: "call and apply invoke functions with a given this, bind returns a new function." },
  { id: 42, question: "What is the difference between shallow copy and reference copy?", answer: "Shallow copy duplicates the object structure, while reference copy points to the same object." },
  { id: 43, question: "What is the difference between undefined and not defined?", answer: "Undefined means declared but not assigned, not defined means not declared at all." },
  { id: 44, question: "What is the difference between mutable and immutable objects?", answer: "Mutable objects can be changed, immutable objects cannot." },
  { id: 45, question: "What is the difference between function scope and block scope?", answer: "Function scope applies to var, block scope applies to let and const." },
  { id: 46, question: "What is the difference between shallow copy and deep copy in arrays?", answer: "Shallow copy copies references, deep copy duplicates nested values." },
  { id: 47, question: "What is the difference between Object.freeze and Object.seal?", answer: "freeze prevents changes, seal allows changes but not additions or removals." },
  { id: 48, question: "What is the difference between Object.assign and spread operator?", answer: "Both copy properties, but the spread operator provides a more concise syntax." },
  { id: 49, question: "What is the difference between synchronous and asynchronous functions?", answer: "Synchronous functions execute sequentially, while asynchronous functions can perform operations without blocking execution." },
  { id: 50, question: "What is the difference between deep copy and shallow copy in objects?", answer: "Deep copy duplicates nested objects, shallow copy only copies references to nested objects." },

  { id: 51, question: "What is React?", answer: "React is a JavaScript library for building user interfaces." },
  { id: 52, question: "What is JSX?", answer: "JSX is a syntax extension that allows you to write HTML-like code inside JavaScript." },
  { id: 53, question: "What are props in React?", answer: "Props are read-only values passed from a parent component to a child component." },
  { id: 54, question: "What is state in React?", answer: "State is data managed inside a component that can change over time and cause the component to re-render." },
  { id: 55, question: "What is the useState hook?", answer: "useState is a React Hook used to add and manage state in functional components." },
  { id: 56, question: "What is the useEffect hook?", answer: "useEffect is a React Hook used to perform side effects such as API calls, subscriptions, and DOM updates." },
  { id: 57, question: "What is the Virtual DOM?", answer: "The Virtual DOM is an in-memory representation of the real DOM that React uses to efficiently update the UI." },
  { id: 58, question: "What is a component in React?", answer: "A component is a reusable piece of UI that can contain its own logic, structure, and data." },
  { id: 59, question: "What are functional components?", answer: "Functional components are JavaScript functions that return JSX to describe the UI." },
  { id: 60, question: "What are class components?", answer: "Class components are JavaScript classes that extend React.Component and can manage state and lifecycle methods." },
  { id: 61, question: "What is component re-rendering?", answer: "Re-rendering is the process of React calling a component again to update its UI when its state or props change." },
  { id: 62, question: "What is the difference between props and state?", answer: "Props are passed from a parent component and are read-only, while state is managed inside a component and can change." },
  { id: 63, question: "What is conditional rendering?", answer: "Conditional rendering means displaying different UI elements based on a condition." },
  { id: 64, question: "How do you render a list in React?", answer: "Lists are commonly rendered using the JavaScript map() method to create elements from an array." },
  { id: 65, question: "Why are keys used in React lists?", answer: "Keys help React identify which list items have changed, been added, or removed." },
  { id: 66, question: "What is the key prop in React?", answer: "The key prop is a unique identifier given to elements in a list so React can efficiently track them." },
  { id: 67, question: "What is event handling in React?", answer: "Event handling allows React components to respond to user actions such as clicks, typing, and form submissions." },
  { id: 68, question: "How are events handled in React?", answer: "Events are handled by passing functions to event props such as onClick, onChange, and onSubmit." },
  { id: 69, question: "What is a SyntheticEvent?", answer: "SyntheticEvent is React's cross-browser wrapper around the browser's native event system." },
  { id: 70, question: "What is a controlled component?", answer: "A controlled component is a form element whose value is controlled by React state." },
  { id: 71, question: "What is an uncontrolled component?", answer: "An uncontrolled component stores its form data in the DOM instead of React state and is commonly accessed using refs." },
  { id: 72, question: "What is useRef?", answer: "useRef is a React Hook used to store a mutable value or access a DOM element without causing a re-render." },
  { id: 73, question: "What is prop drilling?", answer: "Prop drilling is passing props through multiple intermediate components to reach a deeply nested component." },
  { id: 74, question: "What is Context API?", answer: "Context API allows data to be shared between components without passing props through every intermediate component." },
  { id: 75, question: "What is useContext?", answer: "useContext is a React Hook used to access values provided by a React Context." },
  { id: 76, question: "What is lifting state up?", answer: "Lifting state up means moving shared state to the closest common parent component so multiple child components can use it." },
  { id: 77, question: "What is a Fragment in React?", answer: "A Fragment allows multiple elements to be grouped without adding an extra DOM element." },
  { id: 78, question: "What is React.Fragment?", answer: "React.Fragment is a component used to group multiple elements without creating an additional DOM node." },
  { id: 79, question: "What is the difference between React and JavaScript?", answer: "JavaScript is a programming language, while React is a JavaScript library used mainly for building user interfaces." },
  { id: 80, question: "What is the difference between React and ReactDOM?", answer: "React provides the core functionality for creating components, while ReactDOM provides methods for rendering React components into the browser DOM." },
  { id: 81, question: "What is createRoot in React?", answer: "createRoot creates a React root that allows a React application to render components into a DOM element." },
  { id: 82, question: "What is the purpose of package.json in a React project?", answer: "package.json stores project information, scripts, dependencies, and configuration for a React application." },
  { id: 83, question: "What is npm in React?", answer: "npm is a package manager used to install dependencies and run scripts in React projects." },
  { id: 84, question: "What is Vite?", answer: "Vite is a modern frontend build tool used to quickly create and develop React applications." },
  { id: 85, question: "What is a React Hook?", answer: "A Hook is a special React function that allows functional components to use features such as state and lifecycle-related functionality." },
  { id: 86, question: "What are the rules of Hooks?", answer: "Hooks should be called only at the top level of React functions and only from React components or custom Hooks." },
  { id: 87, question: "What is a custom Hook?", answer: "A custom Hook is a reusable JavaScript function that uses React Hooks to share stateful logic between components." },
  { id: 88, question: "What is useMemo?", answer: "useMemo is a Hook that memoizes a calculated value and recomputes it when its dependencies change." },
  { id: 89, question: "What is useCallback?", answer: "useCallback is a Hook that memoizes a function so that the same function reference can be reused between renders when dependencies have not changed." },
  { id: 90, question: "What is React.memo?", answer: "React.memo is a higher-order component that can prevent unnecessary re-renders when a component's props have not changed." },
  { id: 91, question: "What is an API in React?", answer: "An API allows a React application to communicate with a backend or external service to retrieve or send data." },
  { id: 92, question: "How can you fetch API data in React?", answer: "API data can be fetched using JavaScript methods such as fetch or libraries such as Axios, commonly inside useEffect." },
  { id: 93, question: "What is Axios?", answer: "Axios is a JavaScript library used to make HTTP requests to APIs." },
  { id: 94, question: "What is routing in React?", answer: "Routing allows a React application to display different components or pages based on the current URL." },
  { id: 95, question: "What is React Router?", answer: "React Router is a library used to implement client-side routing in React applications." },
  { id: 96, question: "What is SPA in React?", answer: "SPA stands for Single Page Application, where the application loads a single HTML page and updates its content dynamically without full page reloads." },
  { id: 97, question: "What is the difference between state and context?", answer: "State stores data managed by a component, while Context provides a way to share data across multiple components without passing props manually." },
  { id: 98, question: "What is a higher-order component?", answer: "A higher-order component is a function that takes a component and returns a new component with additional behavior or functionality." },
  { id: 99, question: "What is reconciliation in React?", answer: "Reconciliation is the process React uses to compare the previous UI representation with the new one and determine what needs to be updated in the DOM." },
  { id: 100, question: "Why is React used for frontend development?", answer: "React provides reusable components, efficient UI updates, state management patterns, and a large ecosystem for building interactive web applications." }
]